# Generated by Django 2.1.2 on 2018-11-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=100)),
                ('run', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_n', models.DateField(auto_now_add=True)),
                ('telefono', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('tipo_vivienda', models.CharField(max_length=100)),
            ],
        ),
    ]
