# Generated by Django 2.1.2 on 2018-11-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='id',
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='run',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
